CREATE TABLE AUTHORS (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(20CHAR) NOT NULL
);
-- AUTHORSシーケンス
CREATE SEQUENCE ATH_SEQ;

CREATE TABLE BOOKS (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100CHAR) NOT NULL,
  PRICE NUMBER,
  AUTHOR_ID NUMBER,
  NOTE VARCHAR2(200CHAR)
);
-- BOOKSシーケンス
CREATE SEQUENCE BOK_SEQ;
-- BOOK.AUTHOR_IDにAUTHORS.IDの外部キー制約を追加
ALTER TABLE BOOKS ADD CONSTRAINT FK_ATH_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID) ON DELETE SET NULL;